# Generated by Django 3.2.4 on 2021-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('PM', 'Piedmont'), ('MT', 'Mountains'), ('CP', 'Coastal Plain')], default='NC', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=240, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=240, null=True)),
                ('zones', models.ManyToManyField(related_name='plants', to='garden.GrowingZone')),
            ],
        ),
    ]
